# Generated by Django 4.1.6 on 2023-02-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.TextField(max_length=515, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='review',
            name='direction',
            field=models.CharField(max_length=50, verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=70, verbose_name='Имя'),
        ),
    ]
