# Generated by Django 4.1.6 on 2023-03-04 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landing', '0003_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='topic_name',
            field=models.CharField(max_length=50, verbose_name='Название темы'),
        ),
        migrations.CreateModel(
            name='SubscriptionToCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.section', verbose_name='Курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка на курс',
                'verbose_name_plural': 'Подписка на курс',
                'unique_together': {('user', 'course')},
            },
        ),
    ]
