# Generated by Django 4.1.6 on 2023-03-29 10:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_section_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='article',
            name='body_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='article',
            name='topic_name_ky',
            field=models.CharField(max_length=80, null=True, verbose_name='Название темы'),
        ),
        migrations.AddField(
            model_name='article',
            name='topic_name_ru',
            field=models.CharField(max_length=80, null=True, verbose_name='Название темы'),
        ),
        migrations.AddField(
            model_name='courseforlanding',
            name='additional_info_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Информация о курсе'),
        ),
        migrations.AddField(
            model_name='courseforlanding',
            name='additional_info_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Информация о курсе'),
        ),
        migrations.AddField(
            model_name='courseforlanding',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Описание о языке'),
        ),
        migrations.AddField(
            model_name='courseforlanding',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание о языке'),
        ),
        migrations.AddField(
            model_name='courseforlanding',
            name='title_ky',
            field=models.CharField(max_length=123, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='courseforlanding',
            name='title_ru',
            field=models.CharField(max_length=123, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='review',
            name='description_ky',
            field=models.TextField(max_length=515, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='review',
            name='description_ru',
            field=models.TextField(max_length=515, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='review',
            name='direction_ky',
            field=models.CharField(max_length=50, null=True, verbose_name='Направление'),
        ),
        migrations.AddField(
            model_name='review',
            name='direction_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Направление'),
        ),
        migrations.AddField(
            model_name='review',
            name='name_ky',
            field=models.CharField(max_length=70, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='review',
            name='name_ru',
            field=models.CharField(max_length=70, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='section',
            name='description_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Описание для подраздела'),
        ),
        migrations.AddField(
            model_name='section',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание для подраздела'),
        ),
        migrations.AddField(
            model_name='section',
            name='title_ky',
            field=models.CharField(max_length=123, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='section',
            name='title_ru',
            field=models.CharField(max_length=123, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='studyingtime',
            name='title_ky',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='studyingtime',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='article',
            name='topic_name',
            field=models.CharField(max_length=80, verbose_name='Название темы'),
        ),
    ]
