# Generated by Django 4.1.6 on 2023-03-04 08:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_alter_article_topic_name_subscriptiontocourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontocourse',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
