# Generated by Django 4.1.6 on 2023-03-30 14:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_alter_article_body_alter_article_body_ky_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='article',
            name='body_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='article',
            name='body_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Контент'),
        ),
    ]
