# Generated by Django 4.1.6 on 2023-03-10 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_time',
            field=models.TimeField(default=datetime.time(22, 16, 3, 797715), verbose_name='Время сдачи'),
        ),
    ]
