# Generated by Django 4.1.6 on 2023-03-01 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_alter_assignment_due_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_time',
            field=models.TimeField(default=datetime.time(15, 14, 31, 503825), verbose_name='Время сдачи'),
        ),
    ]
