# Generated by Django 4.1.6 on 2023-03-29 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_alter_assignment_due_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_name_ky',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment_name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='instruction_ky',
            field=models.TextField(null=True, verbose_name='Инструкция'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='instruction_ru',
            field=models.TextField(null=True, verbose_name='Инструкция'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='classroom_name_ky',
            field=models.CharField(max_length=99, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='classroom_name_ru',
            field=models.CharField(max_length=99, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='section_ky',
            field=models.CharField(max_length=99, null=True, verbose_name='Раздел'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='section_ru',
            field=models.CharField(max_length=99, null=True, verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_time',
            field=models.TimeField(default=datetime.time(16, 7, 47, 703671), verbose_name='Время сдачи'),
        ),
    ]
