# Generated by Django 4.1.6 on 2023-03-30 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_alter_assignment_due_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_time',
            field=models.TimeField(default=datetime.time(20, 41, 53, 563065), verbose_name='Время сдачи'),
        ),
    ]
