# Generated by Django 4.1.6 on 2023-03-04 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studyingtime',
            options={'verbose_name': 'Время обучения', 'verbose_name_plural': 'Время обучения'},
        ),
    ]
