# Generated by Django 4.1.6 on 2023-02-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srm', '0002_alter_employee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='time',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Утро'), (2, 'День'), (3, 'Вечер'), (4, 'Ночь')], null=True, verbose_name='Время обучения'),
        ),
    ]
