# Generated by Django 4.1.6 on 2023-02-20 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srm', '0003_student_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='srm.currency', verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='student',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='srm.paymentmethod', verbose_name='Способ оплаты'),
        ),
    ]
