# Generated by Django 4.1.6 on 2023-02-20 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srm', '0004_student_currency_student_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='student',
            name='payment_method',
        ),
    ]
