# Generated by Django 4.1.6 on 2023-02-20 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srm', '0005_remove_student_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='time',
        ),
    ]
