# Generated by Django 4.1.6 on 2023-02-20 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srm', '0006_remove_student_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='tariff',
        ),
    ]
