# Generated by Django 4.1.6 on 2023-02-21 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srm', '0007_remove_student_tariff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='course',
        ),
    ]
